import { type PrismaClient } from "@prisma/client";

const topics = [
  "Pop song artist",
  "Video game character",
  "Religious holiday",
  "Disney princess",
  "TV series",
  "American president",
  "Animated film",
  "Social media platform",
  "Film genre",
  "Weapon of mass destruction",
  "Asian dish",
  "Flying creature",
  "Spice/herb",
  "Carnival Ride",
  "Phobia",
  "Tourist destination",
  "Boy band",
  "Traffic sign",
  "Dance style",
  "Café",
  "Striped animal",
  "String instrument",
  "Flightless bird",
  "Shoe brand",
  "Song released this year",
  "Mythological creature",
  "Clothing brand",
  "Car part",
  "Metric unit",
  "3-letter acronym",
  "Asian language",
  "Sharp item",
  "Video game console",
  "Processed food",
  "Allergy",
  "African country",
  "American state",
  "Star Wars character",
  "Fantasy film",
  "Post-secondary school",
  "Phone app",
  "Book genre",
  "Proper noun",
  "Fast food restaurant",
  "Disease",
  "Car brand",
  "Negative emotion",
  "Rapper",
  "Bank",
  "Mammal",
  "Multiple of 4",
  "French word",
  "Historical event",
  "European dish",
  "Religious figure",
  "Wind instrument",
  "Soft drink brand",
  "Things that spin",
  "Imperial unit",
  "Kids TV Series",
  "Pixar character",
  "South American country",
  "Book series",
  "Composer",
  "Fictional weapon",
  "Celestial body",
  "Explosive material",
  "Arachnid",
  "Famous Painting",
  "Spanish word",
  "Crime",
  "Shampoo brand",
  "Mythological flying creature",
  "Birthstone ",
  "Muscle",
  "Candle scent",
  "Billionaire",
  "Spy/secret agent",
  "X-men character",
  "Film Director",
  "Dog breed",
  "Mountain range",
  "Old-school tech",
  "Magical item",
  "Pronoun",
  "Fungus",
  "Conifer",
  "Marsupial",
  "Sports shoe brand",
  "McDonald's mascot",
  "Apple product",
  "Internet browser",
  "Nocturnal Creature",
  "Queen",
  "Aquatic mammal",
  "Disney Song",
  "Bladed weapon",
  "Sidekick",
  "Wizard",
  "Cartoon",
  "Santa's reindeer",
  "Medicine",
  "Chocolate brand",
  "National anthem",
  "Fabric",
  "Tropical Island Destination",
  "Predatory fish",
  "First world problem",
  "Zodiac sign",
  "Gas station",
  "Driving hazard",
  "University",
  "Musical film",
  "Percussion instrument",
  "Word that begins with Z",
  "Jedi",
  "Asian country",
  "Sea Creature",
  "Library",
  "Waterfall",
];

export const seedDefaultDeck = async (dbClient: PrismaClient) => {
  const cards = await dbClient.card.createMany({
    data: topics.map((topic, i) => ({
      deckId: "default",
      shape1: i % 8,
      topic,
    })),
  });
  console.log(cards);
};
