services:
  server:
    build:
      context: ./server
      target: dev
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./server/src:/app/src
      - ./shared:/app/shared
      - ./server/src/prisma:/app/src/prisma
  tests:
    build: 
      context: . 
    volumes:
      - ./server:/app/server
      - ./client:/app/client
      - ./vitest.workspace.ts:/app/vitest.workspace.ts
    tty: true

