services:
  server:
    environment:
      - PORT=${PORT}
    build:
      context: .
      target: dev
      dockerfile: Dockerfile.server
      args:
        - DATABASE_URL=${DATABASE_URL}
    ports:
      - 3000:${PORT}
      - 9229:9229
    volumes:
      - ./server/src:/app/src
      - ./server/src/prisma:/app/src/prisma
      - ./shared:/app/shared
  tests:
    build: 
      context: .
      args:
        - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./server:/app/server
      - ./client:/app/client
      - ./vitest.workspace.ts:/app/vitest.workspace.ts
    tty: true

